@startuml
class Sepatu {
  +id: int
  +nama: String
  +kondisi: String
  +getKeterangan(): String
}

class Peminjam {
  +id: int
  +nama: String
  +meminjamSepatu(): void
}

class Petugas {
  +id: int
  +nama: String
  +mengelolaSepatu(): void
}

class Admin {
  +id: int
  +nama: String
  +mengelolaDataPeminjam(): void
}

Sepatu "1" -- "0..*" Peminjam : meminjam
Sepatu "1" -- "0..*" Petugas : mengelola
Sepatu "1" -- "0..1" Admin : mengelola

@enduml
