@startuml
actor Peminjam
actor Petugas
actor Admin

Peminjam --> (Melihat Sepatu)
Peminjam --> (Meminjam Sepatu)
Petugas --> (Mengelola Sepatu)
Admin --> (Mengelola Data Peminjam)

(Memesan Sepatu) .> (Meminjam Sepatu) : <<include>>
(Meminjam Sepatu) .> (Pengembalian Sepatu) : <<include>>

@enduml
